/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Personas.Colegio;
import Principal.Controlador;
import javax.swing.JFrame;

/**
 *
 * @author lgtjo
 */
public class Administrador_Configuracion extends javax.swing.JFrame {

    
    private Controlador controlador;
    private Colegio colegio;
    private JFrame ventana;
    
    /**
     * Creates new form Administrador_Configuracion
     */
    public Administrador_Configuracion() {
        initComponents();
        
    }

    public Administrador_Configuracion(Controlador controlador,JFrame ventana) {
        this.controlador = controlador;
        this.ventana = ventana;
        initComponents();
        ventana.setVisible(false);
    }
    
    private void modificar_inicio(){
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }
    
    public Colegio colegio(){
        return this.colegio;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JSlogan = new javax.swing.JTextArea();
        JButton_Imagen = new javax.swing.JButton();
        JButton_Slogan = new javax.swing.JButton();
        JButton_Ciclo = new javax.swing.JButton();
        JCiclo = new javax.swing.JTextField();
        JUrl_Imagen = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setUndecorated(true);

        jLabel1.setText("Ruta_Imagen");

        jLabel2.setText("Slogan");

        jLabel3.setText("Ciclo");

        JSlogan.setColumns(20);
        JSlogan.setRows(5);
        jScrollPane1.setViewportView(JSlogan);

        JButton_Imagen.setText("Cambiar ");
        JButton_Imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ImagenActionPerformed(evt);
            }
        });

        JButton_Slogan.setText("Aceptar");
        JButton_Slogan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_SloganActionPerformed(evt);
            }
        });

        JButton_Ciclo.setText("Aceptar");
        JButton_Ciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_CicloActionPerformed(evt);
            }
        });

        JUrl_Imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUrl_ImagenActionPerformed(evt);
            }
        });

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(JUrl_Imagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JButton_Imagen))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(JCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JButton_Slogan)
                                    .addComponent(JButton_Ciclo))
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jScrollPane1)))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JButton_Imagen)
                    .addComponent(JUrl_Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JButton_Slogan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton_Ciclo)
                    .addComponent(JCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_CicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_CicloActionPerformed
        String texto_ciclo = this.JCiclo.getText();
        this.controlador.colegio.setCiclo(texto_ciclo);
        this.controlador.serializarColegio();
    }//GEN-LAST:event_JButton_CicloActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JButton_SloganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_SloganActionPerformed
        String texto_slogan = this.JSlogan.getText();
        this.controlador.colegio.setSlogan(texto_slogan);
        this.controlador.serializarColegio();

    }//GEN-LAST:event_JButton_SloganActionPerformed

    private void JButton_ImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ImagenActionPerformed
        String ruta_imagen = this.JUrl_Imagen.getText();
        this.controlador.colegio.setRuta_imagen(ruta_imagen);
        this.controlador.serializarColegio();
    }//GEN-LAST:event_JButton_ImagenActionPerformed

    private void JUrl_ImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUrl_ImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JUrl_ImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador_Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador_Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador_Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador_Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador_Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_Ciclo;
    private javax.swing.JButton JButton_Imagen;
    private javax.swing.JButton JButton_Slogan;
    private javax.swing.JTextField JCiclo;
    private javax.swing.JTextArea JSlogan;
    private javax.swing.JTextField JUrl_Imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
